//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgmap_province
    {
        public int gid { get; set; }
        public string ten_tinh { get; set; }
        public Nullable<int> orderindex { get; set; }
        public Nullable<int> vungid { get; set; }
        public string luuvucid { get; set; }
        public System.Guid tinh_uuid { get; set; }
        public Nullable<int> ordervung { get; set; }
        public Nullable<int> luuvuc_ngaplut_id { get; set; }
        public Nullable<int> matinh_satlo { get; set; }
    }
}
