//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgmap_commune
    {
        public int gid { get; set; }
        public string ten_xa { get; set; }
        public Nullable<int> huyen_id { get; set; }
        public Nullable<int> tinh_id { get; set; }
        public Nullable<float> hesokhau { get; set; }
        public Nullable<double> x_vido { get; set; }
        public Nullable<double> y_kinhdo { get; set; }
    
        public virtual bgmap_district bgmap_district { get; set; }
    }
}
