//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_canal
    {
        public long id { get; set; }
        public System.Guid mahieu { get; set; }
        public string ten { get; set; }
        public Nullable<int> xa_id { get; set; }
        public Nullable<int> huyen_id { get; set; }
        public Nullable<int> tinh_id { get; set; }
        public Nullable<int> httn_id { get; set; }
        public Nullable<int> loaict_id { get; set; }
        public Nullable<int> dvql_id { get; set; }
        public Nullable<int> luuvucsong_id { get; set; }
        public string nguon_goc { get; set; }
        public string donvi_tinh { get; set; }
        public Nullable<int> loai_taisan_id { get; set; }
        public Nullable<int> nam_xaydung { get; set; }
        public Nullable<int> nam_khaithac { get; set; }
        public Nullable<int> nam_bangiao { get; set; }
        public Nullable<float> dientich_dat { get; set; }
        public Nullable<float> dientich_san { get; set; }
        public Nullable<float> nguyen_gia { get; set; }
        public Nullable<float> tyle_haomon { get; set; }
        public Nullable<float> giatri_conlai { get; set; }
        public Nullable<bool> tinhtrang_taisan { get; set; }
        public Nullable<int> song_id { get; set; }
        public string ma_qhns { get; set; }
        public Nullable<int> type_nguyengia { get; set; }
        public Nullable<int> isdangxaydung { get; set; }
        public Nullable<float> gtcanhbao_mnchancongtrinh { get; set; }
        public Nullable<System.Guid> httn_config { get; set; }
        public Nullable<float> nangluc_lua { get; set; }
        public Nullable<float> nangluc_raumau { get; set; }
        public Nullable<float> nangluc_cndaingay { get; set; }
        public Nullable<float> nangluc_thuysan { get; set; }
        public Nullable<float> kinhdo { get; set; }
        public Nullable<float> vido { get; set; }
        public Nullable<System.Guid> duan_ref { get; set; }
        public Nullable<System.Guid> hethong_ref { get; set; }
        public string sohieukenh { get; set; }
        public Nullable<float> caododay { get; set; }
        public Nullable<float> dodoc_daykenh { get; set; }
        public string ondinh_rori { get; set; }
        public Nullable<float> cd_hieudung { get; set; }
        public string cr_longkenh { get; set; }
        public Nullable<float> cr_bokenh { get; set; }
        public Nullable<float> cc_longkenh { get; set; }
        public Nullable<float> chieuday_thanh { get; set; }
        public Nullable<float> chieuday_day { get; set; }
        public Nullable<float> cr_dayngoai { get; set; }
        public Nullable<float> cd_kenhkiencohoa { get; set; }
        public string loaikenh { get; set; }
        public Nullable<int> capkenh { get; set; }
        public string chatlieu { get; set; }
        public Nullable<float> caodo_tuoi { get; set; }
        public Nullable<float> dientich_tuoi { get; set; }
        public Nullable<float> luulg_tke { get; set; }
        public Nullable<float> luulg_tte { get; set; }
        public string kt_matcat { get; set; }
        public Nullable<float> vttb_dongchay { get; set; }
        public Nullable<System.Guid> reservoir_id { get; set; }
        public string diadiem { get; set; }
        public string lytrinhtu { get; set; }
        public string lytrinhden { get; set; }
        public string vitri { get; set; }
        public Nullable<float> dientich_tuoi_tichluy { get; set; }
        public Nullable<float> luulg_toida { get; set; }
        public Nullable<float> luulg_toithieu { get; set; }
        public Nullable<int> canal_id { get; set; }
        public string taptoado { get; set; }
        public Nullable<int> giaidoan_th { get; set; }
        public Nullable<int> loaimatcat { get; set; }
        public Nullable<float> hs_nham { get; set; }
        public Nullable<float> hs_mai { get; set; }
        public Nullable<float> docao_vuotantoan { get; set; }
        public Nullable<float> dosau_mn_tk { get; set; }
        public Nullable<float> dosau_mn_toida { get; set; }
        public Nullable<float> dosau_mn_toithieu { get; set; }
        public Nullable<float> vtdc_lonnhat { get; set; }
        public Nullable<float> vtdc_nhonhat { get; set; }
        public Nullable<float> ct_doandaukenh { get; set; }
        public Nullable<float> dorong_botrai { get; set; }
        public Nullable<float> dorong_bophai { get; set; }
        public Nullable<int> trangthai { get; set; }
        public string ghichu { get; set; }
        public Nullable<double> chieudai { get; set; }
        public Nullable<double> chieucao { get; set; }
        public string clndk_kichthuoc { get; set; }
        public string clndk_hientrang { get; set; }
        public string hientrang { get; set; }
        public Nullable<int> temp_id { get; set; }
        public string donviquanly { get; set; }
        public string capkenh_temp { get; set; }
        public Nullable<float> sokm_kenhdat { get; set; }
        public Nullable<float> sokm_daxuongcap { get; set; }
        public Nullable<float> sokm_contot { get; set; }
        public Nullable<int> capkenh_id { get; set; }
        public Nullable<float> nangluc { get; set; }
        public string chieurong { get; set; }
        public string kichthuoc { get; set; }
        public string diemdau { get; set; }
        public string diemcuoi { get; set; }
        public string vitricoc { get; set; }
        public string caitao { get; set; }
        public string goithau { get; set; }
    }
}
