//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_denchieusang
    {
        public long id { get; set; }
        public System.Guid mahieu { get; set; }
        public string ten { get; set; }
        public Nullable<int> xa_id { get; set; }
        public Nullable<int> huyen_id { get; set; }
        public Nullable<int> tinh_id { get; set; }
        public Nullable<int> httn_id { get; set; }
        public Nullable<int> loaict_id { get; set; }
        public Nullable<int> dvql_id { get; set; }
        public Nullable<int> luuvucsong_id { get; set; }
        public string nguon_goc { get; set; }
        public string donvi_tinh { get; set; }
        public Nullable<int> loai_taisan_id { get; set; }
        public Nullable<int> nam_xaydung { get; set; }
        public Nullable<int> nam_khaithac { get; set; }
        public Nullable<int> nam_bangiao { get; set; }
        public Nullable<float> dientich_dat { get; set; }
        public Nullable<float> dientich_san { get; set; }
        public Nullable<float> nguyen_gia { get; set; }
        public Nullable<float> tyle_haomon { get; set; }
        public Nullable<float> giatri_conlai { get; set; }
        public Nullable<bool> tinhtrang_taisan { get; set; }
        public Nullable<int> song_id { get; set; }
        public string ma_qhns { get; set; }
        public Nullable<int> type_nguyengia { get; set; }
        public Nullable<int> isdangxaydung { get; set; }
        public Nullable<float> gtcanhbao_mnchancongtrinh { get; set; }
        public Nullable<System.Guid> httn_config { get; set; }
        public Nullable<float> nangluc_lua { get; set; }
        public Nullable<float> nangluc_raumau { get; set; }
        public Nullable<float> nangluc_cndaingay { get; set; }
        public Nullable<float> nangluc_thuysan { get; set; }
        public Nullable<float> kinhdo { get; set; }
        public Nullable<float> vido { get; set; }
        public Nullable<System.Guid> duan_ref { get; set; }
        public Nullable<System.Guid> hethong_ref { get; set; }
        public string diadiem { get; set; }
        public string thuockenh { get; set; }
        public string thuocho { get; set; }
        public string loaict { get; set; }
        public string loaiden { get; set; }
        public string chieucao { get; set; }
        public string loaigeom { get; set; }
        public string goithau { get; set; }
        public string loai { get; set; }
        public string tenduong { get; set; }
        public string dongngat { get; set; }
    }
}
