//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_hoga
    {
        public long id { get; set; }
        public System.Guid mahieu { get; set; }
        public string ten { get; set; }
        public Nullable<int> xa_id { get; set; }
        public Nullable<int> huyen_id { get; set; }
        public Nullable<int> tinh_id { get; set; }
        public Nullable<int> httn_id { get; set; }
        public Nullable<int> loaict_id { get; set; }
        public Nullable<int> dvql_id { get; set; }
        public Nullable<int> luuvucsong_id { get; set; }
        public string nguon_goc { get; set; }
        public string donvi_tinh { get; set; }
        public Nullable<int> loai_taisan_id { get; set; }
        public Nullable<int> nam_xaydung { get; set; }
        public Nullable<int> nam_khaithac { get; set; }
        public Nullable<int> nam_bangiao { get; set; }
        public Nullable<float> dientich_dat { get; set; }
        public Nullable<float> dientich_san { get; set; }
        public Nullable<float> nguyen_gia { get; set; }
        public Nullable<float> tyle_haomon { get; set; }
        public Nullable<float> giatri_conlai { get; set; }
        public Nullable<bool> tinhtrang_taisan { get; set; }
        public Nullable<int> song_id { get; set; }
        public string ma_qhns { get; set; }
        public Nullable<int> type_nguyengia { get; set; }
        public Nullable<int> isdangxaydung { get; set; }
        public Nullable<float> gtcanhbao_mnchancongtrinh { get; set; }
        public Nullable<System.Guid> httn_config { get; set; }
        public Nullable<float> nangluc_lua { get; set; }
        public Nullable<float> nangluc_raumau { get; set; }
        public Nullable<float> nangluc_cndaingay { get; set; }
        public Nullable<float> nangluc_thuysan { get; set; }
        public Nullable<float> kinhdo { get; set; }
        public Nullable<float> vido { get; set; }
        public Nullable<System.Guid> duan_ref { get; set; }
        public Nullable<System.Guid> hethong_ref { get; set; }
        public string diadiem { get; set; }
        public string thuockenh { get; set; }
        public string thuocho { get; set; }
        public string loaict { get; set; }
        public string loaihoga { get; set; }
        public string chieucao { get; set; }
        public string loaigeom { get; set; }
        public string gocngoatd1d2 { get; set; }
        public string congvaod1 { get; set; }
        public string congrad2 { get; set; }
        public string caodomatdat { get; set; }
        public string caododaycong { get; set; }
        public string caododayga { get; set; }
        public string chieucaoh1 { get; set; }
        public string ketcau { get; set; }
        public string goithau { get; set; }
        public string tenduong { get; set; }
        public string thuoccong { get; set; }
        public string congvaod3 { get; set; }
        public string ctu_r3_r5 { get; set; }
        public string ctu_r3_r6 { get; set; }
        public string caododay_e1 { get; set; }
        public string caododay_e2 { get; set; }
        public string caododay_e3 { get; set; }
        public string caododay_e4 { get; set; }
        public string caododay_e5 { get; set; }
        public string gocngoatd3d2 { get; set; }
        public string gocngoatd4d2 { get; set; }
        public string gocngoatd5d2 { get; set; }
        public string duongkinhd1 { get; set; }
        public string duongkinhd2 { get; set; }
        public string duongkinhd3 { get; set; }
        public string duongkinhd4 { get; set; }
        public string kyhieu { get; set; }
    }
}
