//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_irrigation_sewer
    {
        public long id { get; set; }
        public System.Guid mahieu { get; set; }
        public string ten { get; set; }
        public Nullable<int> xa_id { get; set; }
        public Nullable<int> huyen_id { get; set; }
        public Nullable<int> tinh_id { get; set; }
        public Nullable<int> httn_id { get; set; }
        public Nullable<int> loaict_id { get; set; }
        public Nullable<int> dvql_id { get; set; }
        public Nullable<int> luuvucsong_id { get; set; }
        public string nguon_goc { get; set; }
        public string donvi_tinh { get; set; }
        public Nullable<int> loai_taisan_id { get; set; }
        public Nullable<int> nam_xaydung { get; set; }
        public Nullable<int> nam_khaithac { get; set; }
        public Nullable<int> nam_bangiao { get; set; }
        public Nullable<float> dientich_dat { get; set; }
        public Nullable<float> dientich_san { get; set; }
        public Nullable<float> nguyen_gia { get; set; }
        public Nullable<float> tyle_haomon { get; set; }
        public Nullable<float> giatri_conlai { get; set; }
        public Nullable<bool> tinhtrang_taisan { get; set; }
        public Nullable<int> song_id { get; set; }
        public string ma_qhns { get; set; }
        public Nullable<int> type_nguyengia { get; set; }
        public Nullable<int> isdangxaydung { get; set; }
        public Nullable<float> gtcanhbao_mnchancongtrinh { get; set; }
        public Nullable<System.Guid> httn_config { get; set; }
        public Nullable<float> nangluc_lua { get; set; }
        public Nullable<float> nangluc_raumau { get; set; }
        public Nullable<float> nangluc_cndaingay { get; set; }
        public Nullable<float> nangluc_thuysan { get; set; }
        public Nullable<float> kinhdo { get; set; }
        public Nullable<float> vido { get; set; }
        public Nullable<System.Guid> duan_ref { get; set; }
        public Nullable<System.Guid> hethong_ref { get; set; }
        public Nullable<int> dam_id { get; set; }
        public Nullable<float> luulg_tke { get; set; }
        public Nullable<float> luulg_tte { get; set; }
        public Nullable<int> loaicong { get; set; }
        public string ht_tieunang { get; set; }
        public string tbi_tieunang { get; set; }
        public string ketcau { get; set; }
        public string khaudien { get; set; }
        public Nullable<float> kt_cuavao { get; set; }
        public Nullable<float> kt_cuara { get; set; }
        public Nullable<float> chieudai { get; set; }
        public string chedo_vanhanh { get; set; }
        public Nullable<int> socuacong { get; set; }
        public Nullable<float> ct_daycong_thgluu { get; set; }
        public Nullable<float> ct_daycong_haluu { get; set; }
        public Nullable<float> ct_nguongcong { get; set; }
        public string vvh_thgluu { get; set; }
        public string vvh_haluu { get; set; }
        public string kt_cuacong { get; set; }
        public Nullable<bool> cong_hongnang { get; set; }
        public Nullable<bool> cong_dangmo { get; set; }
        public string htdm_thuongluu { get; set; }
        public string hientrang { get; set; }
        public Nullable<int> nam_hoanthanh { get; set; }
        public Nullable<int> nam_suachua { get; set; }
        public Nullable<int> canal_id { get; set; }
        public string diadiem { get; set; }
        public string vitri { get; set; }
        public Nullable<float> dttuoi_tke { get; set; }
        public Nullable<float> dttieu_tke { get; set; }
        public Nullable<float> dtnganman_tke { get; set; }
        public Nullable<float> dttuoi_tte { get; set; }
        public Nullable<float> dttieu_tte { get; set; }
        public Nullable<float> dtnganman_tte { get; set; }
        public Nullable<System.Guid> reservoir_id { get; set; }
        public string kichthuoc { get; set; }
        public string hinhthuc { get; set; }
        public Nullable<System.Guid> dam_uuid { get; set; }
        public string capcong { get; set; }
        public string lytrinh { get; set; }
        public string chatlieu { get; set; }
        public string hinhdang_cong { get; set; }
        public string ghichu { get; set; }
        public string donviquanly { get; set; }
        public Nullable<int> temp_id { get; set; }
        public string thuockenh { get; set; }
        public string loaict { get; set; }
        public string thuocho { get; set; }
        public string chieucao_daycuaxa { get; set; }
        public string chieucao_dinhke { get; set; }
        public string diemdau { get; set; }
        public string diemcuoi { get; set; }
        public string loaicongten { get; set; }
        public string thuocduong { get; set; }
        public string tenduong { get; set; }
        public string goithau { get; set; }
        public string chieurong { get; set; }
        public string chieucao { get; set; }
        public string duongkinh { get; set; }
        public string vatlieu { get; set; }
        public string dosaucong { get; set; }
        public Nullable<double> loai_1a1 { get; set; }
        public Nullable<double> loai_1a2 { get; set; }
        public Nullable<double> loai_1b1 { get; set; }
        public Nullable<double> loai_1b2 { get; set; }
        public Nullable<double> tong { get; set; }
        public Nullable<double> h_z2_z3 { get; set; }
        public Nullable<double> htb_z0_z1 { get; set; }
    }
}
