//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_pump_station
    {
        public long id { get; set; }
        public System.Guid mahieu { get; set; }
        public string ten { get; set; }
        public Nullable<int> xa_id { get; set; }
        public Nullable<int> huyen_id { get; set; }
        public Nullable<int> tinh_id { get; set; }
        public Nullable<int> httn_id { get; set; }
        public Nullable<int> loaict_id { get; set; }
        public Nullable<int> dvql_id { get; set; }
        public Nullable<int> luuvucsong_id { get; set; }
        public string nguon_goc { get; set; }
        public string donvi_tinh { get; set; }
        public Nullable<int> loai_taisan_id { get; set; }
        public Nullable<int> nam_xaydung { get; set; }
        public Nullable<int> nam_khaithac { get; set; }
        public Nullable<int> nam_bangiao { get; set; }
        public Nullable<float> dientich_dat { get; set; }
        public Nullable<float> dientich_san { get; set; }
        public Nullable<float> nguyen_gia { get; set; }
        public Nullable<float> tyle_haomon { get; set; }
        public Nullable<float> giatri_conlai { get; set; }
        public Nullable<bool> tinhtrang_taisan { get; set; }
        public Nullable<int> song_id { get; set; }
        public string ma_qhns { get; set; }
        public Nullable<int> type_nguyengia { get; set; }
        public Nullable<int> isdangxaydung { get; set; }
        public Nullable<float> gtcanhbao_mnchancongtrinh { get; set; }
        public Nullable<System.Guid> httn_config { get; set; }
        public Nullable<float> nangluc_lua { get; set; }
        public Nullable<float> nangluc_raumau { get; set; }
        public Nullable<float> nangluc_cndaingay { get; set; }
        public Nullable<float> nangluc_thuysan { get; set; }
        public Nullable<float> kinhdo { get; set; }
        public Nullable<float> vido { get; set; }
        public Nullable<System.Guid> duan_ref { get; set; }
        public Nullable<System.Guid> hethong_ref { get; set; }
        public Nullable<float> congtongbom { get; set; }
        public Nullable<float> tongcongsuat { get; set; }
        public string somaybom { get; set; }
        public Nullable<float> dttuoi_tke { get; set; }
        public Nullable<float> dttuoi_tte { get; set; }
        public Nullable<float> ct_mucnuoctk { get; set; }
        public Nullable<float> ct_daybehut { get; set; }
        public Nullable<float> ct_mucnuocbx { get; set; }
        public Nullable<float> ct_tamongxa { get; set; }
        public Nullable<float> ct_thanhbx { get; set; }
        public Nullable<float> ct_sanmay { get; set; }
        public Nullable<float> cotnuoc { get; set; }
        public string tbi_dieukhien { get; set; }
        public string tietdien_duongday { get; set; }
        public Nullable<float> chieudai_dgday { get; set; }
        public Nullable<int> namxaydung { get; set; }
        public string diadiem { get; set; }
        public Nullable<float> dtcapns_tke { get; set; }
        public Nullable<float> dttieu_tte { get; set; }
        public Nullable<float> dtcapns_tte { get; set; }
        public Nullable<float> dttieu_tke { get; set; }
        public Nullable<int> loai_trambom { get; set; }
        public Nullable<float> congsuattk { get; set; }
        public Nullable<float> congsuattk_tieu { get; set; }
        public Nullable<System.Guid> reservoir_id { get; set; }
        public Nullable<float> chieu_rong { get; set; }
        public Nullable<float> chieu_cao { get; set; }
        public string loaimay { get; set; }
        public string mahieumay { get; set; }
        public Nullable<double> luuluong_motmay { get; set; }
        public Nullable<double> ct_dongco { get; set; }
        public Nullable<double> ct_mucnuocbh { get; set; }
        public Nullable<double> chieudai_onghut { get; set; }
        public Nullable<double> ct_tamonghut { get; set; }
        public Nullable<double> dientich_behut { get; set; }
        public Nullable<double> chieudai_ongxa { get; set; }
        public Nullable<double> dientich_bexa { get; set; }
        public string ly_trinh { get; set; }
        public string clndk_kichthuoc { get; set; }
        public string clndk_hientrang { get; set; }
        public string hientrang { get; set; }
        public Nullable<int> captrambom { get; set; }
        public string ghichu { get; set; }
        public Nullable<long> temp_id { get; set; }
        public string donviquanly { get; set; }
        public string quymo { get; set; }
        public string dientichtuoi { get; set; }
        public string dientichtieu { get; set; }
        public string ketcau { get; set; }
        public string dienthoai { get; set; }
        public string fax { get; set; }
        public string mucnuocbexa { get; set; }
        public string mucnuocbehut { get; set; }
        public string khoangcachtim { get; set; }
        public string hieusuat { get; set; }
        public string ct_sansuachua { get; set; }
        public string ct_bobehut { get; set; }
        public string chieudaibehut { get; set; }
        public string chieurongbehut { get; set; }
        public string ct_daybexa { get; set; }
        public string ct_bobexa { get; set; }
        public string chieudaibexa { get; set; }
        public string chieurongbexa { get; set; }
        public string ct_tuongbexa { get; set; }
        public string congapluc { get; set; }
        public string luuluongtt { get; set; }
        public Nullable<float> congsuattb { get; set; }
        public string vitri { get; set; }
        public Nullable<float> cotap { get; set; }
        public string goithau { get; set; }
    }
}
