//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class odaninhthuanEntities : DbContext
    {
        public odaninhthuanEntities()
            : base("name=odaninhthuanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<iw_boviaviahe> iw_boviaviahe { get; set; }
        public DbSet<iw_canal> iw_canal { get; set; }
        public DbSet<iw_coc> iw_coc { get; set; }
        public DbSet<iw_denchieusang> iw_denchieusang { get; set; }
        public DbSet<iw_diemngap> iw_diemngap { get; set; }
        public DbSet<iw_gieng> iw_gieng { get; set; }
        public DbSet<iw_hoga> iw_hoga { get; set; }
        public DbSet<iw_hotrongcay> iw_hotrongcay { get; set; }
        public DbSet<iw_irrigation_sewer> iw_irrigation_sewer { get; set; }
        public DbSet<iw_nhamayxulynuocthai> iw_nhamayxulynuocthai { get; set; }
        public DbSet<iw_pump_station> iw_pump_station { get; set; }
        public DbSet<iw_reservoir> iw_reservoir { get; set; }
        public DbSet<iw_timduong> iw_timduong { get; set; }
        public DbSet<iw_trucuuhoa> iw_trucuuhoa { get; set; }
        public DbSet<iw_vuotnoi> iw_vuotnoi { get; set; }
        public DbSet<tbl_danhmuc_duan> tbl_danhmuc_duan { get; set; }
        public DbSet<tbl_danhmuc_hethong> tbl_danhmuc_hethong { get; set; }
        public DbSet<bgmap_commune> bgmap_commune { get; set; }
        public DbSet<bgmap_district> bgmap_district { get; set; }
        public DbSet<bgmap_province> bgmap_province { get; set; }
        public DbSet<tbl_duytubaoduong> tbl_duytubaoduong { get; set; }
        public DbSet<tbl_tutailieu_files> tbl_tutailieu_files { get; set; }
        public DbSet<tbl_tutailieu_files_detail> tbl_tutailieu_files_detail { get; set; }
        public DbSet<tbl_tutailieu_files_types> tbl_tutailieu_files_types { get; set; }
        public DbSet<tbl_tutailieu_folder> tbl_tutailieu_folder { get; set; }
        public DbSet<tbl_tutailieu_history> tbl_tutailieu_history { get; set; }
        public DbSet<tbl_tutailieu_thuoctinh> tbl_tutailieu_thuoctinh { get; set; }
        public DbSet<tbl_tutailieu_thuoctinh_danhmuc> tbl_tutailieu_thuoctinh_danhmuc { get; set; }
        public DbSet<tbl_tutailieu_thuoctinh_detail> tbl_tutailieu_thuoctinh_detail { get; set; }
        public DbSet<tbl_tutailieu_tree> tbl_tutailieu_tree { get; set; }
        public DbSet<tbl_tutailieu_tree_default> tbl_tutailieu_tree_default { get; set; }
        public DbSet<tbl_tutailieu_users_files_folder> tbl_tutailieu_users_files_folder { get; set; }
    }
}
