//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tutailieu_files_detail
    {
        public long ttl_files_detail_id { get; set; }
        public string ttl_files_detail_localpath { get; set; }
        public string ttl_files_detail_remotepath { get; set; }
        public string ttl_files_detail_resize_localpath { get; set; }
        public string ttl_files_detail_resize_remotepath { get; set; }
        public string ttl_files_detail_type { get; set; }
        public Nullable<long> ttl_files_detail_size { get; set; }
        public Nullable<int> ttl_files_detail_viewed { get; set; }
        public Nullable<int> ttl_files_detail_downloaded { get; set; }
    }
}
