//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tutailieu_thuoctinh
    {
        public long tt_id { get; set; }
        public string tt_name { get; set; }
        public Nullable<int> tt_form { get; set; }
        public Nullable<int> tt_parentid { get; set; }
        public string tt_map_table { get; set; }
        public string tt_map_column { get; set; }
        public string tt_field_table { get; set; }
        public string tt_field_id { get; set; }
        public string tt_field_name { get; set; }
        public string tt_field_where { get; set; }
        public string tt_field_order { get; set; }
        public string tt_field_changer { get; set; }
        public string tt_field_holder { get; set; }
        public Nullable<int> tt_orderby { get; set; }
        public Nullable<int> tt_type { get; set; }
        public Nullable<int> tt_data_type { get; set; }
        public string tt_unit { get; set; }
        public bool tt_default { get; set; }
        public bool tt_search { get; set; }
        public bool tt_show { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> last_modified_at { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<int> deleted_status { get; set; }
    }
}
