//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tutailieu_files_types
    {
        public long ttl_ftype_id { get; set; }
        public string ttl_ftype_type { get; set; }
        public string ttl_ftype_name { get; set; }
    }
}
