//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tutailieu_users_files_folder
    {
        public long ttl_uf_id { get; set; }
        public Nullable<System.Guid> ttl_uf_users { get; set; }
        public Nullable<long> ttl_uf_files_folder { get; set; }
        public Nullable<int> ttl_uf_role { get; set; }
        public int ttl_uf_status { get; set; }
        public bool ttl_uf_star { get; set; }
    }
}
