//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tutailieu_folder
    {
        public long ttl_tree_id { get; set; }
        public string ttl_tree_ten { get; set; }
        public Nullable<System.Guid> ttl_tree_user_creator { get; set; }
        public Nullable<System.DateTime> ttl_tree_date_created { get; set; }
        public Nullable<System.Guid> ttl_tree_user_modifier { get; set; }
        public Nullable<System.DateTime> ttl_tree_date_modified { get; set; }
        public Nullable<int> ttl_tree_form { get; set; }
        public int ttl_tree_type { get; set; }
        public Nullable<int> ttl_tree_tochucid { get; set; }
        public Nullable<System.Guid> ttl_tree_object { get; set; }
        public Nullable<int> ttl_tree_object_type { get; set; }
        public Nullable<int> ttl_tree_df_id { get; set; }
        public Nullable<int> ttl_folder_origin { get; set; }
        public Nullable<int> ttl_folder_icon { get; set; }
        public string ttl_folder_localpath { get; set; }
        public string ttl_folder_remotepath { get; set; }
    }
}
