//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_duytubaoduong
    {
        public long id { get; set; }
        public System.Guid ct_uuid { get; set; }
        public string kyhieu { get; set; }
        public Nullable<int> phanloairef { get; set; }
        public string loaicongtrinh { get; set; }
        public string tinh_id { get; set; }
        public string huyen_id { get; set; }
        public string diadiem { get; set; }
        public Nullable<float> tongchieudai { get; set; }
        public string giaiphapkythuat { get; set; }
        public string vatlieuxaydung { get; set; }
        public Nullable<float> kinhphi { get; set; }
        public Nullable<int> namkehoach { get; set; }
        public Nullable<int> namthuchien { get; set; }
        public Nullable<int> namhoanthanh { get; set; }
        public Nullable<int> nguon { get; set; }
        public Nullable<int> duyet { get; set; }
        public string soqd { get; set; }
        public string ngayqd { get; set; }
        public string anhtruoc { get; set; }
        public string anhsau { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createdat { get; set; }
        public string lastmodifiedby { get; set; }
        public Nullable<System.DateTime> lastmodifiedat { get; set; }
    }
}
