//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tutailieu_history
    {
        public long ttl_ls_id { get; set; }
        public Nullable<long> ttl_ls_ttl_tree_id { get; set; }
        public string ttl_ls_tbl_tutailieu_files { get; set; }
        public string ttl_ls_tbl_tutailieu_folder { get; set; }
        public string ttl_ls_tbl_tutailieu_users_files_folder { get; set; }
        public Nullable<System.Guid> ttl_ls_users { get; set; }
        public Nullable<System.DateTime> ttl_ls_thoigian { get; set; }
        public Nullable<long> ttl_ls_folder_id { get; set; }
        public string ttl_ls_folder_name { get; set; }
        public Nullable<int> ttl_ls_type { get; set; }
    }
}
