//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tutailieu_tree_default
    {
        public long ttl_tree_df_id { get; set; }
        public string ttl_tree_df_ten { get; set; }
        public Nullable<long> ttl_tree_df_pid { get; set; }
        public Nullable<int> ttl_tree_df_sort { get; set; }
        public Nullable<int> ttl_tree_df_form { get; set; }
        public int ttl_tree_df_type { get; set; }
        public Nullable<int> ttl_tree_df_tochucid { get; set; }
        public Nullable<int> ttl_tree_df_object_type { get; set; }
        public Nullable<bool> ttl_tree_df_default { get; set; }
        public Nullable<int> ttl_tree_df_origin { get; set; }
        public Nullable<int> ttl_tree_df_icon { get; set; }
        public string ttl_tree_df_localpath { get; set; }
        public string ttl_tree_df_remotepath { get; set; }
    }
}
