//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odaninhthuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tutailieu_thuoctinh_detail
    {
        public long ttdt_id { get; set; }
        public Nullable<long> ttdt_tt_id { get; set; }
        public Nullable<long> ttdt_tree_id { get; set; }
        public string ttdt_value { get; set; }
        public Nullable<bool> ttdt_display { get; set; }
        public Nullable<int> ttdt_orderby { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> last_modified_at { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<int> deleted_status { get; set; }
    }
}
